/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/components/App.vue')['default']
    BottomNavbar: typeof import('./src/components/BottomNavbar/index.vue')['default']
    Button: typeof import('./src/components/Button/index.vue')['default']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    Input: typeof import('./src/components/Input/index.vue')['default']
    QRScan: typeof import('./src/components/QRScan/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SafeArea: typeof import('./src/components/SafeArea/index.vue')['default']
    TicketCard: typeof import('./src/components/TicketCard/index.vue')['default']
  }
}
