# Generated by Django 3.2.8 on 2023-04-11 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Билет атауы')),
                ('expiration_date', models.DateTimeField(verbose_name='Мерзімнің өту күні')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеттер',
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='UserTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_time', models.DateTimeField(auto_now_add=True, verbose_name='Сатып алған уақыт')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Сатып алушы')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.ticket', verbose_name='Билет')),
            ],
            options={
                'verbose_name': 'Билет сатып алушы',
                'verbose_name_plural': 'Билет сатып алғандар',
                'db_table': 'user_ticket',
            },
        ),
    ]
