# Generated by Django 3.2.8 on 2023-06-14 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_remove_user_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Атауы')),
                ('description', models.CharField(max_length=254, verbose_name='Атауы')),
                ('quantity', models.PositiveIntegerField(verbose_name='Саны')),
                ('production_date', models.DateTimeField(verbose_name='Өндірілген күні')),
                ('expiration_date', models.DateTimeField(verbose_name='Мерзімнің өту күні')),
                ('supplier', models.CharField(max_length=60, verbose_name='Жеткізуші')),
                ('purchase_price', models.PositiveIntegerField(verbose_name='Сатып алынған бағасы')),
                ('selling_price', models.PositiveIntegerField(verbose_name='Сату бағасы')),
                ('shelf_position', models.CharField(max_length=60, verbose_name='Жеткізуші')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Иесі')),
            ],
            options={
                'verbose_name': 'Зат',
                'verbose_name_plural': 'Заттар',
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='Атауы')),
                ('color', models.CharField(max_length=22, verbose_name='Шрифт түсі')),
                ('background_color', models.CharField(max_length=22, verbose_name='Фон түсі')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Құрушысы')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Тегтер',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='ItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item', verbose_name='Зат')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Зат тег',
                'verbose_name_plural': 'Зат тег',
                'db_table': 'item_tag',
            },
        ),
    ]
