# Generated by Django 3.2.8 on 2023-06-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='item/image/', verbose_name='Суреты'),
        ),
    ]
