# Generated by Django 3.2.8 on 2023-06-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Сипаттама'),
        ),
        migrations.AlterField(
            model_name='item',
            name='expiration_date',
            field=models.DateTimeField(verbose_name='Мерзімнің өту күн'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='item/image/', verbose_name='Сурет'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Атау'),
        ),
        migrations.AlterField(
            model_name='item',
            name='production_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Өндірілген күн'),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Сатып алынған баға'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Саны'),
        ),
        migrations.AlterField(
            model_name='item',
            name='selling_price',
            field=models.PositiveIntegerField(verbose_name='Сату баға'),
        ),
        migrations.AlterField(
            model_name='item',
            name='shelf_position',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Жеткізуші'),
        ),
        migrations.AlterField(
            model_name='item',
            name='supplier',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Жеткізуші'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=12, verbose_name='Атау'),
        ),
    ]
