# Generated by Django 3.2.8 on 2023-04-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=254, verbose_name='Құпиясөз'),
            preserve_default=False,
        ),
    ]
