# Generated by Django 3.2.8 on 2023-04-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230425_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Аты-жөн'),
        ),
    ]
