# Generated by Django 3.2.8 on 2023-04-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Аты-жөн'),
        ),
    ]
